version: "3"

services:
  database:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: etl
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - 3306:3306
    volumes:
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - sde_network
  
  loader:
    image: etl_run
    container_name: etl_run
    build:
      context: ./containers/loader/
    volumes:
      - ./:/opt/sde
    networks:
      - sde_network


networks:
  sde_network:
    driver: bridge