version: "3.8"

services:
  database:
    image: mysql:latest
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: etl
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - 3306:3306
    volumes:
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  

